export CUDA_VISIBLE_DEVICES=7
MODEL_DIR="${MOPPIT_MODEL_DIR:-$HOME/model_weights/moppit}"
SCORE_BATCH_SIZE="${MOPPIT_SCORE_BATCH_SIZE:-32}"
PPL_BATCH_SIZE="${MOPPIT_PPL_BATCH_SIZE:-1024}"

moppit-generate \
--model-dir "$MODEL_DIR" \
--protein-seq 'IVEGSDAEIGMSPWQVMLFRKSPQELLCGASLISDRWVLTAAHCLLYPPWDKNFTENDLLVRIGKHSRTRYERNIEKISMLEKIYIHPRYNWRENLDRDIALMKLKKPVAFSDYIHPVCLPDRETAASLLQAGYKGRVTGWGNLKETGQPSVLQVVNLPIVERPVCKDSTRIRITDNMFCAGYKPDEGKRGDACEGDSGGPFVMKSPFNNRWYQMGIVSWGEGCDRDGKYGFYTHVFRLKKWIQKVIDQFGE' \
--peptide-length 11 \
--motif '[18,23,59,67,68,69,70,76,77]' \
--top-k 3 \
--num-binders 50 \
--num-display 10 \
--score-batch-size "$SCORE_BATCH_SIZE" \
--ppl-batch-size "$PPL_BATCH_SIZE" \
--output generated_binders.csv
