export CUDA_VISIBLE_DEVICES=7
MODEL_DIR="${MOPPIT_MODEL_DIR:-$HOME/model_weights/moppit}"

moppit-predict \
--model-dir "$MODEL_DIR" \
--target 'IVEGSDAEIGMSPWQVMLFRKSPQELLCGASLISDRWVLTAAHCLLYPPWDKNFTENDLLVRIGKHSRTRYERNIEKISMLEKIYIHPRYNWRENLDRDIALMKLKKPVAFSDYIHPVCLPDRETAASLLQAGYKGRVTGWGNLKETGQPSVLQVVNLPIVERPVCKDSTRIRITDNMFCAGYKPDEGKRGDACEGDSGGPFVMKSPFNNRWYQMGIVSWGEGCDRDGKYGFYTHVFRLKKWIQKVIDQFGE' \
--binder 'GYEEIPEEYLQ' \
--output predicted_sites.json
